---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-interpreter-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create", "delete", "update", "patch", "watch", "exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
subjects:
- kind: ServiceAccount
  name: code-interpreter-sa
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: code-interpreter-service
spec:
  serviceAccountName: code-interpreter-sa
  containers:
  - name: code-interpreter-service
    image: localhost/bee-code-interpreter:local
    ports:
    - containerPort: 50051
