#!/bin/bash
shopt -s dotglob

SOURCE_CODE_TMP_DIR=$(mktemp -d)
PIP_TMP_DIR=$(mktemp -d)

cat >$SOURCE_CODE_TMP_DIR/script.py

GUESSED_DEPENDENCIES=$(cd $SOURCE_CODE_TMP_DIR && upm guess 2>/dev/null)

if [ ! -z "$GUESSED_DEPENDENCIES" ]; then
    PYTHONUSERBASE=$PIP_TMP_DIR pip install --no-cache-dir $GUESSED_DEPENDENCIES >/dev/null 2>/dev/null
fi

PYTHONPATH=$PIP_TMP_DIR:$PYTHONPATH timeout ${APP_EXECUTION_TIMEOUT:-60} python <$SOURCE_CODE_TMP_DIR/script.py
RETVAL=$?

rm -rf /tmp/*

exit $RETVAL
