#!/bin/bash
shopt -s dotglob

SOURCE_CODE_TMP_DIR=$(mktemp -d)

cat >$SOURCE_CODE_TMP_DIR/script.py

GUESSED_DEPENDENCIES=$(cd $SOURCE_CODE_TMP_DIR && upm guess 2>/dev/null)

if [ ! -z "$GUESSED_DEPENDENCIES" ]; then
    PIP_TMP_DIR=$(mktemp -d)
    PYTHONUSERBASE=$PIP_TMP_DIR pip install --user --no-cache-dir $GUESSED_DEPENDENCIES >/dev/null 2>/dev/null
    export PYTHONPATH=$(realpath $PIP_TMP_DIR/lib/**/site-packages)
fi

timeout ${APP_EXECUTION_TIMEOUT:-60} python <$SOURCE_CODE_TMP_DIR/script.py
RETVAL=$?

rm -rf /tmp/*

exit $RETVAL
