name: Multi-Platform Docker Build and Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ICR
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Build and push bee-code-interpreter
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-interpreter:latest
          ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-interpreter:${{ steps.get_version.outputs.VERSION }}
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-interpreter:buildcache
        cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-interpreter:buildcache,mode=max

    - name: Build and push bee-code-executor
      uses: docker/build-push-action@v6
      with:
        context: ./executor
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-executor:latest
          ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-executor:${{ steps.get_version.outputs.VERSION }}
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-executor:buildcache
        cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-code-executor:buildcache,mode=max
